import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

veriseti = [
['Tarhana', 'Cacik', 'Besamelli Tavuk', 'Makarna'],
['Baklava', 'Besamelli Tavuk', 'Makarna', 'Tarhana'],
['Tarhana', 'Rus Salatasi', 'Makarna', 'Besamelli Tavuk'],
['Tarhana', 'Enginar', 'Makarna', 'Besamelli Tavuk'],
['Tarhana', 'Yogurtlu Semizotu', 'Makarna', 'Besamelli Tavuk'],
['Tarhana', 'Pirinc Pilavi', 'Besamelli Tavuk', 'Cigkofte'],
['Tarhana', 'Cacik', 'Pirinc Pilavi', 'Besamelli Tavuk'],
['Tarhana', 'Baklava', 'Pirinc Pilavi', 'Besamelli Tavuk'],
['Tarhana', 'Rus Salatasi', 'Pirinc Pilavi', 'Besamelli Tavuk'],
['Tarhana', 'Enginar', 'Pirinc Pilavi', 'Besamelli Tavuk'],
['Tarhana', 'Yogurtlu Semizotu', 'Pirinc Pilavi', 'Besamelli Tavuk'],
['Tarhana', 'Cigkofte', 'Bulgur Pilavi', 'Besamelli Tavuk'],
['Tarhana', 'Cacik', 'Bulgur Pilavi', 'Besamelli Tavuk'],
['Tarhana', 'Baklava', 'Bulgur Pilavi', 'Besamelli Tavuk'],
['Tarhana', 'Rus Salatasi', 'Bulgur Pilavi', 'Besamelli Tavuk'],
['Tarhana', 'Bulgur Pilavi', 'Enginar', 'Besamelli Tavuk'],
['Tarhana', 'Yogurtlu Semizotu', 'Bulgur Pilavi', 'Besamelli Tavuk'],
['Tarhana', 'Cigkofte', 'Makarna', 'Manti'],
['Tarhana', 'Baklava', 'Makarna', 'Manti'],
['Tarhana', 'Makarna', 'Cacik', 'Manti'],
['Tarhana', 'Rus Salatasi', 'Makarna', 'Manti'],
['Tarhana', 'Enginar', 'Makarna', 'Manti'],
['Tarhana', 'Yogurtlu Semizotu', 'Makarna', 'Manti'],
['Tarhana', 'Cigkofte', 'Pirinc Pilavi', 'Manti'],
['Tarhana', 'Cacik', 'Pirinc Pilavi', 'Manti'],
['Tarhana', 'Baklava', 'Pirinc Pilavi', 'Manti'],
['Tarhana', 'Rus Salatasi', 'Pirinc Pilavi', 'Manti'],
['Tarhana', 'Enginar', 'Pirinc Pilavi', 'Manti'],
['Tarhana', 'Yogurtlu Semizotu', 'Pirinc Pilavi', 'Manti'],
['Tarhana', 'Cigkofte', 'Bulgur Pilavi', 'Manti'],
['Tarhana', 'Cacik', 'Bulgur Pilavi', 'Manti'],
['Tarhana', 'Baklava', 'Bulgur Pilavi', 'Manti'],
['Tarhana', 'Rus Salatasi', 'Bulgur Pilavi', 'Manti'],
['Tarhana', 'Enginar', 'Bulgur Pilavi', 'Manti'],
['Tarhana', 'Yogurtlu Semizotu', 'Bulgur Pilavi', 'Manti'],
['Tarhana', 'Cigkofte', 'Makarna', 'Tavuk Sote'],
['Tarhana', 'Cacik', 'Makarna', 'Tavuk Sote'],
['Tarhana', 'Baklava', 'Makarna', 'Tavuk Sote', 'Ekmek'],
['Tarhana', 'Rus Salatasi', 'Makarna', 'Tavuk Sote', 'Ekmek'],
['Tarhana', 'Enginar', 'Makarna', 'Tavuk Sote', 'Ekmek'],
['Tarhana', 'Yogurtlu Semizotu', 'Makarna', 'Tavuk Sote', 'Ekmek'],
['Tarhana', 'Cigkofte', 'Pirinc Pilavi', 'Tavuk Sote', 'Ekmek'],
['Tarhana', 'Cacik', 'Su', 'Pirinc Pilavi', 'Tavuk Sote', 'Ekmek'],
['Tarhana', 'Baklava', 'Pirinc Pilavi', 'Tavuk Sote', 'Ekmek', 'Su'],
['Tarhana', 'Rus Salatasi', 'Pirinc Pilavi', 'Tavuk Sote', 'Ekmek', 'Su'],
['Tarhana', 'Enginar', 'Enginar', 'Su', 'Tavuk Sote', 'Ekmek'],
['Tarhana', 'Yogurtlu Semizotu', 'Pirinc Pilavi', 'Su', 'Tavuk Sote', 'Ekmek'],
['Mercimek Corbasi', 'Revani', 'Pirinc Pilavi', 'Tavuk Sis', 'Su'],
['Kisir', 'Mercimek Corbasi', 'Pirinc Pilavi', 'Tavuk Sis', 'Su'],
['Sutlac', 'Pirinc Pilavi', 'Mercimek Corbasi', 'Tavuk Sis', 'Su'],
['Pirinc Pilavi', 'Yogurt', 'Mercimek Corbasi', 'Tavuk Sis', 'Su'],
['Revani', 'Bulgur Pilavi', 'Mercimek Corbasi', 'Tavuk Sis', 'Su'],
['Kisir', 'Bulgur Pilavi', 'Mercimek Corbasi', 'Tavuk Sis', 'Su'],
['Sutlac', 'Bulgur Pilavi', 'Mercimek Corbasi', 'Tavuk Sis', 'Su'],
['Yogurt', 'Bulgur Pilavi', 'Mercimek Corbasi', 'Tavuk Sis', 'Su'],
['Makarna', 'Mercimek Corbasi', 'Tavuk Sis', 'Su'],
['Revani', 'Makarna', 'Mercimek Corbasi', 'Tavuk Sis', 'Su'],
['Kisir', 'Makarna', 'Mercimek Corbasi', 'Tavuk Sis', 'Su'],
['Sutlac', 'Makarna', 'Tavuk Sis', 'Mercimek Corbasi', 'Su'],
['Yogurt', 'Makarna', 'Mercimek Corbasi', 'Tavuk Sis', 'Su'],
['Revani', 'Pirinc Pilavi', 'Mercimek Corbasi', 'Kasarli Tavuk', 'Su'],
['Kisir', 'Mercimek Corbasi', 'Pirinc Pilavi', 'Kasarli Tavuk', 'Su'],
['Sutlac', 'Pirinc Pilavi', 'Mercimek Corbasi', 'Kasarli Tavuk', 'Su'],
['Yogurt', 'Mercimek Corbasi', 'Pirinc Pilavi', 'Kasarli Tavuk', 'Su'],
['Revani', 'Mercimek Corbasi', 'Bulgur Pilavi', 'Kasarli Tavuk', 'Su'],
['Kisir', 'Mercimek Corbasi', 'Bulgur Pilavi', 'Kasarli Tavuk'],
['Sutlac', 'Mercimek Corbasi', 'Bulgur Pilavi', 'Kasarli Tavuk'],
['Yogurt', 'Bulgur Pilavi', 'Mercimek Corbasi', 'Kasarli Tavuk', 'Su'],
['Yogurt', 'Bulgur Pilavi', 'Mercimek Corbasi', 'Kasarli Tavuk'],
['Revani', 'Makarna', 'Mercimek Corbasi', 'Kasarli Tavuk', 'Su'],
['Kisir', 'Makarna', 'Mercimek Corbasi', 'Su', 'Kasarli Tavuk'],
['Sutlac', 'Makarna', 'Mercimek Corbasi', 'Kasarli Tavuk', 'Su'],
['Yogurt', 'Mercimek Corbasi', 'Mercimek Corbasi', 'Kasarli Tavuk', 'Su'],
['Revani', 'Mercimek Corbasi', 'Pirinc Pilavi', 'Icli Kofte', 'Su'],
['Kisir', 'Pirinc Pilavi', 'Mercimek Corbasi', 'Icli Kofte', 'Su'],
['Sutlac', 'Mercimek Corbasi', 'Pirinc Pilavi', 'Icli Kofte', 'Su'],
['Yogurt', 'Pirinc Pilavi', 'Mercimek Corbasi', 'Su', 'Icli Kofte'],
['Revani', 'Bulgur Pilavi', 'Mercimek Corbasi', 'Icli Kofte', 'Su'],
['Kisir', 'Bulgur Pilavi', 'Mercimek Corbasi', 'Icli Kofte', 'Su'],
['Revani', 'Bulgur Pilavi', 'Sebze Corbasi', 'Kuru Fasulye', 'Su'],
['Kisir', 'Sebze Corbasi', 'Bulgur Pilavi', 'Kuru Fasulye', 'Su'],
['Sutlac', 'Sebze Corbasi', 'Bulgur Pilavi', 'Kuru Fasulye', 'Su'],
['Yogurt', 'Bulgur Pilavi', 'Kuru Fasulye', 'Sebze Corbasi', 'Su'],
['Revani', 'Makarna', 'Kuru Fasulye', 'Sebze Corbasi', 'Su'],
['Kisir', 'Makarna', 'Sebze Corbasi', 'Kuru Fasulye', 'Su'],
['Sutlac', 'Makarna', 'Kuru Fasulye', 'Sebze Corbasi', 'Su'],
['Yogurt', 'Sebze Corbasi', 'Makarna', 'Kuru Fasulye', 'Su'],
['Makarna', 'Kuru Fasulye', 'Su'],
['Pirinc Pilavi', 'Kuru Fasulye', 'Su'],
['Bulgur Pilavi', 'Kuru Fasulye', 'Su'],
['Kisir', 'Kuru Fasulye', 'Su'],
['Revani', 'Kuru Fasulye', 'Su'],
['Kisir', 'Icli Kofte', 'Su'],
['Sutlac', 'Icli Kofte', 'Su'],
['Sutlac', 'Kisir', 'Icli Kofte', 'Su'],
['Yogurt', 'Kisir', 'Sutlac', 'Icli Kofte', 'Su'],
['Sebze Corbasi', 'Icli Kofte', 'Yogurt', 'Su'],
['Kasarli Tavuk', 'Sebze Corbasi', 'Yogurt', 'Su'],
['Rosto Kofte', 'Sebze Corbasi', 'Bulgur Pilavi', 'Mevsim Salata', 'Su'],
['Rosto Kofte', 'Sebze Corbasi', 'Bulgur Pilavi', 'Kadayif', 'Su'],
['Cigkofte', 'Rosto Kofte', 'Su', 'Sebze Corbasi', 'Bulgur Pilavi'],
['Sebze Corbasi', 'Cacik', 'Rosto Kofte', 'Bulgur Pilavi', 'Su'],
['Makarna', 'Sebze Corbasi', 'Cacik', 'Su', 'Rosto Kofte'],
['Makarna', 'Mevsim Salata', 'Rosto Kofte', 'Sebze Corbasi', 'Su'],
['Sebze Corbasi', 'Cigkofte', 'Rosto Kofte', 'Makarna', 'Su'],
['Sebze Corbasi', 'Kadayif', 'Rosto Kofte', 'Makarna', 'Su'],
['Sebze Corbasi', 'Makarna', 'Kadayif', 'Su', 'Pilic Fileto'],
['Sebze Corbasi', 'Pilic Fileto', 'Makarna', 'Mevsim Salata', 'Su'],
['Sebze Corbasi', 'Makarna', 'Pilic Fileto', 'Cigkofte', 'Su'],
['Sebze Corbasi', 'Cacik', 'Makarna', 'Su', 'Pilic Fileto'],
['Sebze Corbasi', 'Pilic Fileto', 'Makarna', 'Kadayif', 'Su'],
['Sebze Corbasi', 'Makarna', 'Pilic Fileto', 'Su'],
['Sebze Corbasi', 'Makarna', 'Su'],
['Sebze Corbasi', 'Makarna', 'Cigkofte'],
['Sebze Corbasi', 'Cacik', 'Makarna'],
['Mevsim Salata', 'Sebze Corbasi', 'Makarna', 'Su'],
['Sebze Corbasi', 'Makarna', 'Kadayif'],
['Sebze Corbasi', 'Bulgur Pilavi', 'Kadayif', 'Su'],
['Sebze Corbasi', 'Bulgur Pilavi', 'Cacik', 'Su'],
['Ekmek', 'Sebze Corbasi', 'Bulgur Pilavi', 'Cigkofte', 'Su'],
['Pilic Fileto', 'Ekmek', 'Su', 'Sebze Corbasi'],
['Sebze Corbasi', 'Cigkofte', 'Su', 'Pilic Fileto', 'Ekmek'],
['Sebze Corbasi', 'Su', 'Ekmek', 'Pilic Fileto', 'Kadayif'],
['Cigkofte', 'Kadayif', 'Su', 'Sebze Corbasi', 'Pilic Fileto', 'Ekmek'],
['Sebze Corbasi', 'Pilic Fileto', 'Su', 'Ekmek', 'Cacik', 'Kadayif'],
['Sebze Corbasi', 'Su', 'Rosto Kofte', 'Kadayif', 'Ekmek'],
['Su', 'Sebze Corbasi', 'Rosto Kofte', 'Cacik', 'Ekmek'],
['Mevsim Salata', 'Su', 'Ekmek', 'Sebze Corbasi', 'Rosto Kofte'],
['Cacik', 'Sulu Kofte', 'Makarna', 'Cigkofte'],
['Sulu Kofte', 'Cigkofte', 'Makarna', 'Ayran'],
['Sulu Kofte', 'Makarna', 'Cigkofte', 'Yogurt'],
['Sulu Kofte', 'Makarna', 'Cigkofte', 'Yogurt'],
['Sulu Kofte', 'Meyve Suyu', 'Makarna', 'Cigkofte'],
['Sulu Kofte', 'Makarna', 'Cigkofte', 'Salgam'],
['Sulu Kofte', 'Makarna', 'Cigkofte', 'Salata'],
['Sulu Kofte', 'Makarna', 'Cigkofte', 'Ayva Tatlisi'],
['Sulu Kofte', 'Makarna', 'Elma', 'Cigkofte'],
['Sulu Kofte', 'Makarna', 'Cigkofte', 'Portakal'],
['Sulu Kofte', 'Sekerpare', 'Makarna', 'Cigkofte'],
['Sulu Kofte', 'Revani', 'Makarna', 'Cigkofte'],
['Sulu Kofte', 'Makarna', 'Cigkofte', 'Cikolatali Baklava'],
['Sulu Kofte', 'Makarna', 'Cigkofte', 'CobanSalata'],
['Sulu Kofte', 'Makarna', 'Kola', 'Cigkofte'],
['CobanSalata', 'Cacik', 'Makarna', 'Sulu Kofte'],
['CobanSalata', 'Ayva Tatlisi', 'Makarna', 'Sulu Kofte'],
['CobanSalata', 'Ayran', 'Makarna', 'Sulu Kofte'],
['CobanSalata', 'Sekerpare', 'Makarna', 'Sulu Kofte'],
['CobanSalata', 'Armut', 'Makarna', 'Sulu Kofte'],
['CobanSalata', 'Portakal', 'Makarna', 'Sulu Kofte'],
['CobanSalata', 'Elma', 'Makarna', 'Sulu Kofte'],
['CobanSalata', 'Sulu Kofte', 'Cikolatali Baklava', 'Makarna'],
['CobanSalata', 'Revani', 'Makarna', 'Sulu Kofte'],
['Revani', 'Pirinc Pilavi', 'CobanSalata', 'Sulu Kofte'],
['Cikolatali Baklava', 'Pirinc Pilavi', 'CobanSalata', 'Sulu Kofte'],
['Sekerpare', 'Pirinc Pilavi', 'CobanSalata', 'Sulu Kofte'],
['Ayva Tatlisi', 'Pirinc Pilavi', 'CobanSalata', 'Sulu Kofte'],
['Cacik', 'Pirinc Pilavi', 'CobanSalata', 'Sulu Kofte'],
['Elma', 'Pirinc Pilavi', 'CobanSalata', 'Sulu Kofte'],
['Armut', 'Pirinc Pilavi', 'CobanSalata', 'Sulu Kofte'],
['Portakal', 'Sulu Kofte', 'Pirinc Pilavi', 'CobanSalata'],
['Kola', 'Pirinc Pilavi', 'CobanSalata', 'Sulu Kofte'],
['Ayran', 'Pirinc Pilavi', 'CobanSalata', 'Sulu Kofte'],
['Yogurt', 'Pirinc Pilavi', 'CobanSalata', 'Sulu Kofte'],
['Cacik', 'Bulgur Pilavi', 'CobanSalata', 'Sulu Kofte'],
['Cigkofte', 'Bulgur Pilavi', 'CobanSalata', 'Sulu Kofte'],
['Yogurt', 'Bulgur Pilavi', 'CobanSalata', 'Sulu Kofte'],
['Ayran', 'Bulgur Pilavi', 'CobanSalata', 'Sulu Kofte'],
['Sekerpare', 'Bulgur Pilavi', 'CobanSalata', 'Sulu Kofte'],
['Cikolatali Baklava', 'Bulgur Pilavi', 'CobanSalata', 'Sulu Kofte'],
['Revani', 'Bulgur Pilavi', 'CobanSalata', 'Sulu Kofte'],
['Ayva Tatlisi', 'Bulgur Pilavi', 'CobanSalata', 'Sulu Kofte'],
['Bulgur Pilavi', 'Elma', 'CobanSalata', 'Sulu Kofte'],
['Portakal', 'Bulgur Pilavi', 'CobanSalata', 'Sulu Kofte'],
['CobanSalata', 'Sulu Kofte', 'Armut', 'Bulgur Pilavi'],
['CobanSalata', 'Sulu Kofte', 'Salata', 'Bulgur Pilavi'],
['CobanSalata', 'Sulu Kofte', 'Kola', 'Bulgur Pilavi'],
['CobanSalata', 'Sulu Kofte', 'Bulgur Pilavi', 'Salgam'],
['CobanSalata', 'Cacik', 'Bulgur Pilavi', 'Taze Fasulye'],
['Bulgur Pilavi', 'CobanSalata', 'Cigkofte', 'Taze Fasulye'],
['Pirinc Pilavi', 'Bulgur Pilavi', 'Taze Fasulye', 'CobanSalata'],
['Salgam', 'Bulgur Pilavi', 'Taze Fasulye', 'CobanSalata'],
['Kola', 'Bulgur Pilavi', 'Taze Fasulye', 'CobanSalata'],
['CobanSalata', 'Bulgur Pilavi', 'Taze Fasulye', 'Ayran'],
['CobanSalata', 'Bulgur Pilavi', 'Taze Fasulye', 'Yogurt'],
['CobanSalata', 'Ayva Tatlisi', 'Bulgur Pilavi', 'Taze Fasulye'],
['Sekerpare', 'Bulgur Pilavi', 'Taze Fasulye', 'CobanSalata'],
['Cikolatali Baklava', 'Bulgur Pilavi', 'Taze Fasulye', 'CobanSalata'],
['Revani', 'Bulgur Pilavi', 'Taze Fasulye', 'CobanSalata'],
['Portakal', 'Bulgur Pilavi', 'Taze Fasulye', 'CobanSalata'],
['Elma', 'Bulgur Pilavi', 'Taze Fasulye', 'CobanSalata'],
['Armut', 'Bulgur Pilavi', 'Taze Fasulye', 'CobanSalata'],
['Cacik', 'Bulgur Pilavi', 'Cigkofte', 'Taze Fasulye'],
['Cacik', 'Bulgur Pilavi', 'Enginar', 'Taze Fasulye'],
['Cacik', 'Elma', 'Bulgur Pilavi', 'Taze Fasulye'],
['Cacik', 'Portakal', 'Bulgur Pilavi', 'Taze Fasulye'],
['Cacik', 'Armut', 'Bulgur Pilavi', 'Taze Fasulye'],
['Cacik', 'Sekerpare', 'Bulgur Pilavi', 'Taze Fasulye'],
['Cacik', 'Cikolatali Baklava', 'Bulgur Pilavi', 'Taze Fasulye'],
['Ayva Tatlisi', 'Cacik', 'Bulgur Pilavi', 'Taze Fasulye'],
['Revani', 'Cacik', 'Bulgur Pilavi', 'Taze Fasulye'],
['Makarna', 'Cacik', 'Bulgur Pilavi', 'Taze Fasulye'],
['Makarna', 'Kapuska', 'Cacik', 'Cigkofte'],
['Makarna', 'Kapuska', 'Cacik', 'Tursu'],
['Makarna', 'Kapuska', 'Cacik', 'Mevsim Salata'],
['Makarna', 'Kapuska', 'Cacik', 'Sutlac'],
['Kapuska', 'Makarna', 'KibrisTatlisi', 'Cacik'],
['Kapuska', 'Makarna', 'Sobiyet', 'Cacik'],
['Kapuska', 'Makarna', 'KabakTatlisi', 'Cacik'],
['Kapuska', 'Makarna', 'Armut', 'Cacik'],
['Kapuska', 'Makarna', 'Portakal', 'Cacik'],
['Kapuska', 'Makarna', 'Elma', 'Cacik'],
['Kapuska', 'Makarna', 'Ayran', 'Cigkofte'],
['Kapuska', 'Makarna', 'Ayran', 'Cigkofte'],
['Kapuska', 'Kola', 'Cigkofte', 'Makarna'],
['Kapuska', 'CobanSalata', 'Makarna', 'Cigkofte'],
['PatlicanDolmasi', 'Cacik', 'Cigkofte', 'Makarna'],
['PatlicanDolmasi', 'Pirinc Pilavi', 'Cacik', 'Cigkofte'],
['PatlicanDolmasi', 'Ayran', 'Cigkofte', 'Pirinc Pilavi'],
['PatlicanDolmasi', 'Pirinc Pilavi', 'Ayran', 'Cigkofte'],
['PatlicanDolmasi', 'Pirinc Pilavi', 'KabakTatlisi', 'Kola'],
['PatlicanDolmasi', 'Pirinc Pilavi', 'Armut', 'Cacik'],
['PatlicanDolmasi', 'Cacik', 'Pirinc Pilavi', 'Elma'],
['PatlicanDolmasi', 'Pirinc Pilavi', 'Cacik', 'Portakal'],
['PatlicanDolmasi', 'Pirinc Pilavi', 'Tursu', 'Cacik'],
['PatlicanDolmasi', 'Pirinc Pilavi', 'CobanSalata', 'Cacik'],
['Pirinc Pilavi', 'PatlicanEzmesi', 'KoftePatatesPuresi', 'Sobiyet'],
['Pirinc Pilavi', 'PatlicanEzmesi', 'Sutlac', 'KoftePatatesPuresi'],
['Pirinc Pilavi', 'PatlicanEzmesi', 'KabakTatlisi', 'KoftePatatesPuresi'],
['Pirinc Pilavi', 'PatlicanEzmesi', 'KibrisTatlisi', 'KoftePatatesPuresi'],
['Pirinc Pilavi', 'PatlicanEzmesi', 'KoftePatatesPuresi', 'Portakal'],
['Pirinc Pilavi', 'PatlicanEzmesi', 'Elma', 'KoftePatatesPuresi'],
['Pirinc Pilavi', 'PatlicanEzmesi', 'KoftePatatesPuresi', 'Armut'],
['Pirinc Pilavi', 'PatlicanEzmesi', 'Mevsim Salata', 'KoftePatatesPuresi'],
['Pirinc Pilavi', 'PatlicanEzmesi', 'Tursu', 'KoftePatatesPuresi'],
['Pirinc Pilavi', 'PatlicanEzmesi', 'KoftePatatesPuresi', 'CobanSalata'],
['Pirinc Pilavi', 'PatlicanEzmesi', 'Cigkofte', 'KoftePatatesPuresi'],
['Pirinc Pilavi', 'PatlicanEzmesi', 'KoftePatatesPuresi', 'Cacik'],
['Bulgur Pilavi', 'PatlicanEzmesi', 'KoftePatatesPuresi', 'Cacik'],
['Bulgur Pilavi', 'PatlicanEzmesi', 'Cigkofte', 'KoftePatatesPuresi'],
['Bulgur Pilavi', 'KoftePatatesPuresi', 'PatlicanEzmesi', 'Tursu'],
['Bulgur Pilavi', 'PatlicanEzmesi', 'KoftePatatesPuresi', 'CobanSalata'],
['Bulgur Pilavi', 'PatlicanEzmesi', 'KoftePatatesPuresi', 'Mevsim Salata'],
['Bulgur Pilavi', 'KoftePatatesPuresi', 'PatlicanEzmesi', 'Sobiyet'],
['Portakal', 'PatlicanEzmesi', 'Bulgur Pilavi', 'KoftePatatesPuresi'],
['PatlicanEzmesi', 'Bulgur Pilavi', 'KoftePatatesPuresi', 'Armut'],
['Bulgur Pilavi', 'PatlicanEzmesi', 'KoftePatatesPuresi', 'Elma'],
['KibrisTatlisi', 'PatlicanEzmesi', 'Bulgur Pilavi', 'KoftePatatesPuresi'],
['Bulgur Pilavi', 'PatlicanEzmesi', 'KoftePatatesPuresi', 'Sutlac'],
['Bulgur Pilavi', 'PatlicanEzmesi', 'KabakTatlisi', 'KoftePatatesPuresi'],
['Bulgur Pilavi', 'PatlicanEzmesi', 'KoftePatatesPuresi', 'Portakal'],
['Armut', 'PatlicanEzmesi', 'Bulgur Pilavi', 'KoftePatatesPuresi'],
['Bulgur Pilavi', 'PatlicanEzmesi', 'Elma', 'KoftePatatesPuresi'],
['Bulgur Pilavi', 'PatlicanEzmesi', 'Sutlac', 'KoftePatatesPuresi'],
['Bulgur Pilavi', 'PatlicanEzmesi', 'KibrisTatlisi', 'KoftePatatesPuresi'],
['PatlicanEzmesi', 'KabakTatlisi', 'Bulgur Pilavi', 'KoftePatatesPuresi'],
['Bulgur Pilavi', 'PatlicanEzmesi', 'Cigkofte', 'KoftePatatesPuresi'],
['Bulgur Pilavi', 'PatlicanEzmesi', 'Cacik', 'KoftePatatesPuresi'],
['Bulgur Pilavi', 'PatlicanEzmesi', 'KoftePatatesPuresi', 'Mevsim Salata'],
['CobanSalata', 'PatlicanEzmesi', 'Bulgur Pilavi', 'KoftePatatesPuresi'],
['Tursu', 'PatlicanEzmesi', 'Bulgur Pilavi', 'KoftePatatesPuresi'],
['PatlicanEzmesi', 'Sobiyet', 'Bulgur Pilavi', 'KoftePatatesPuresi'],
['PatlicanEzmesi', 'Cacik', 'KoftePatatesPuresi', 'Makarna'],
['PatlicanEzmesi', 'Cigkofte', 'KoftePatatesPuresi', 'Makarna'],
['Tursu', 'PatlicanEzmesi', 'Makarna', 'KoftePatatesPuresi'],
['CobanSalata', 'PatlicanEzmesi', 'KoftePatatesPuresi', 'Makarna'],
['Mevsim Salata', 'PatlicanEzmesi', 'KoftePatatesPuresi', 'Makarna'],
['Armut', 'PatlicanEzmesi', 'KoftePatatesPuresi', 'Makarna'],
['Elma', 'PatlicanEzmesi', 'Makarna', 'KoftePatatesPuresi'],
['Portakal', 'PatlicanEzmesi', 'Makarna', 'KoftePatatesPuresi'],
['Sutlac', 'PatlicanEzmesi', 'Makarna', 'KoftePatatesPuresi'],
['KibrisTatlisi', 'PatlicanEzmesi', 'Makarna', 'KoftePatatesPuresi'],
['KabakTatlisi', 'PatlicanEzmesi', 'Makarna', 'KoftePatatesPuresi'],
['Sobiyet', 'PatlicanEzmesi', 'Makarna', 'KoftePatatesPuresi'],
['Cacik', 'PatlicanEzmesi', 'Makarna', 'PatlicanDolmasi'],
['Cacik', 'PatlicanEzmesi', 'PatlicanDolmasi', 'Makarna'],
['Cigkofte', 'PatlicanEzmesi', 'PatlicanDolmasi', 'Makarna'],
['Tursu', 'PatlicanEzmesi', 'Makarna', 'PatlicanDolmasi'],
['CobanSalata', 'PatlicanEzmesi', 'PatlicanDolmasi', 'Makarna'],
['Mevsim Salata', 'PatlicanDolmasi', 'PatlicanEzmesi', 'Makarna'],
['Armut', 'PatlicanEzmesi', 'PatlicanDolmasi', 'Makarna'],
['Elma', 'PatlicanEzmesi', 'PatlicanDolmasi', 'Makarna'],
['Portakal', 'PatlicanEzmesi', 'PatlicanDolmasi', 'Makarna'],
['KabakTatlisi', 'PatlicanEzmesi', 'PatlicanDolmasi', 'Makarna'],
['KibrisTatlisi', 'PatlicanEzmesi', 'PatlicanDolmasi', 'Makarna'],
['Sutlac', 'PatlicanEzmesi', 'PatlicanDolmasi', 'Makarna'],
['Sobiyet', 'PatlicanEzmesi', 'PatlicanDolmasi', 'Makarna'],
['KabakTatlisi', 'Portakal', 'Bulgur Pilavi', 'PatlicanDolmasi'],
['Elma', 'Portakal', 'Bulgur Pilavi', 'PatlicanDolmasi'],
['Bulgur Pilavi', 'KibrisTatlisi', 'Elma', 'PatlicanDolmasi'],
['Elma', 'KibrisTatlisi', 'Bulgur Pilavi', 'PatlicanDolmasi'],
['PatlicanEzmesi', 'PatlicanDolmasi', 'KibrisTatlisi', 'Bulgur Pilavi'],
['PatlicanEzmesi', 'PatlicanDolmasi', 'Elma', 'Bulgur Pilavi'],
['PatlicanEzmesi', 'Cigkofte', 'PatlicanDolmasi', 'Bulgur Pilavi'],
['PatlicanEzmesi', 'PatlicanDolmasi', 'Armut', 'Bulgur Pilavi'],
['KabakTatlisi', 'Armut', 'Bulgur Pilavi', 'PatlicanDolmasi'],
['KibrisTatlisi', 'Armut', 'PatlicanDolmasi', 'Bulgur Pilavi'],
['CobanSalata', 'Armut', 'Bulgur Pilavi', 'PatlicanDolmasi'],
['CobanSalata', 'Elma', 'Bulgur Pilavi', 'PatlicanDolmasi'],
['CobanSalata', 'KibrisTatlisi', 'Bulgur Pilavi', 'PatlicanDolmasi'],
['CobanSalata', 'Portakal', 'Bulgur Pilavi', 'PatlicanDolmasi'],
['CobanSalata', 'KabakTatlisi', 'Bulgur Pilavi', 'PatlicanDolmasi'],
['CobanSalata', 'KibrisTatlisi', 'Bulgur Pilavi', 'PatlicanDolmasi'],
['CobanSalata', 'Cigkofte', 'Bulgur Pilavi', 'PatlicanDolmasi'],
['KabakTatlisi', 'Cigkofte', 'Bulgur Pilavi', 'PatlicanDolmasi'],
['Cigkofte', 'Sutlac', 'Bulgur Pilavi', 'PatlicanDolmasi'],
['KibrisTatlisi', 'Cigkofte', 'Bulgur Pilavi', 'PatlicanDolmasi'],
['Cigkofte', 'Armut', 'Bulgur Pilavi', 'PatlicanDolmasi'],
['Cigkofte', 'Elma', 'Bulgur Pilavi', 'PatlicanDolmasi'],
['KabakTatlisi', 'Cigkofte', 'Bulgur Pilavi', 'PatlicanDolmasi'],
['Sobiyet', 'Cigkofte', 'Bulgur Pilavi', 'PatlicanDolmasi'],
['Armut', 'Cigkofte', 'Bulgur Pilavi', 'Kapuska'],
['Bulgur Pilavi', 'Kapuska', 'Cigkofte', 'Elma'],
['Portakal', 'Cigkofte', 'Bulgur Pilavi', 'Kapuska'],
['Cigkofte', 'KabakTatlisi', 'Bulgur Pilavi', 'Kapuska'],
['PatlicanEzmesi', 'Cigkofte', 'Bulgur Pilavi', 'Kapuska'],
['Sutlac', 'Cigkofte', 'Bulgur Pilavi', 'Kapuska'],
['KibrisTatlisi', 'Cigkofte', 'Bulgur Pilavi', 'Kapuska'],
['CobanSalata', 'Cigkofte', 'Bulgur Pilavi', 'Kapuska'],
['CobanSalata', 'Elma', 'Bulgur Pilavi', 'Kapuska'],
['CobanSalata', 'Portakal', 'Bulgur Pilavi', 'Kapuska'],
['CobanSalata', 'Armut', 'Bulgur Pilavi', 'Kapuska'],
['CobanSalata', 'Sutlac', 'Bulgur Pilavi', 'Kapuska'],
['CobanSalata', 'KabakTatlisi', 'Bulgur Pilavi', 'Kapuska'],
['CobanSalata', 'PatlicanEzmesi', 'Kapuska', 'Bulgur Pilavi'],
['Armut', 'PatlicanEzmesi', 'Kapuska', 'Bulgur Pilavi'],
['Armut', 'KabakTatlisi', 'Bulgur Pilavi', 'Kapuska'],
['Armut', 'Sutlac', 'Bulgur Pilavi', 'Kapuska'],
['Armut', 'KibrisTatlisi', 'Bulgur Pilavi', 'Kapuska'],
['Armut', 'Elma', 'Bulgur Pilavi', 'Kapuska'],
['Ayran', 'Ayva Tatlisi', 'Pirinc Pilavi', 'Pilic Kroket'],
['Pilic Kroket', 'Yogurt', 'Ayva Tatlisi', 'Pirinc Pilavi'],
['Cigkofte', 'Ayva Tatlisi', 'Pilic Kroket', 'Pirinc Pilavi'],
['Cacik', 'Ayva Tatlisi', 'Pirinc Pilavi', 'Pilic Kroket'],
['Ayva Tatlisi', 'Pirinc Pilavi', 'Pirasa', 'Pilic Kroket'],
['CobanSalata', 'Pilic Kroket', 'Pirinc Pilavi', 'Ayva Tatlisi'],
['Ayva Tatlisi', 'Meyve Suyu', 'Pilic Kroket', 'Pirinc Pilavi'],
['Ayva Tatlisi', 'Pilic Kroket', 'Enginar', 'Pirinc Pilavi'],
['Meyve Suyu', 'Pilic Kroket', 'Pirinc Pilavi', 'Elma'],
['Sekerpare', 'Pilic Kroket', 'Pirinc Pilavi', 'Meyve Suyu'],
['Portakal', 'Salgam', 'Pilic Kroket', 'Pirinc Pilavi'],
['Pilic Kroket', 'Pirinc Pilavi', 'Salgam', 'Revani'],
['Pilic Kroket', 'CobanSalata', 'Pirinc Pilavi', 'Maden Suyu'],
['Pilic Kroket', 'Cigkofte', 'Salgam', 'Pirinc Pilavi'],
['Pirinc Pilavi', 'Ayran', 'Pirasa', 'Pilic Kroket'],
['Pirinc Pilavi', 'Yogurt', 'Pilic Kroket', 'Pirasa'],
['Elma', 'Pilic Kroket', 'Yogurt', 'Pirinc Pilavi'],
['Elma', 'Ayran', 'Pirinc Pilavi', 'Pilic Kroket'],
['Pirinc Pilavi', 'Meyve Suyu', 'Pilic Kroket', 'Elma'],
['Pirinc Pilavi', 'Cacik', 'Pilic Kroket', 'Elma'],
['Pirinc Pilavi', 'Cacik', 'Elma', 'Pilic Kroket'],
['Elma', 'Pilic Kroket', 'Pirinc Pilavi', 'Soguk Cay'],
['Pirinc Pilavi', 'Cacik', 'Pilic Kroket', 'Ayva Tatlisi'],
['Pirinc Pilavi', 'Pilic Kroket', 'Armut', 'Cacik'],
['Pirinc Pilavi', 'Cacik', 'Pilic Kroket', 'Sekerpare'],
['Pirinc Pilavi', 'Cacik', 'Cikolatali Baklava', 'Pilic Kroket'],
['Pirinc Pilavi', 'Cacik', 'Revani', 'Pilic Kroket'],
['Bulgur Pilavi', 'Cacik', 'Pilic Kroket', 'PatlicanEzmesi'],
['Pirinc Pilavi', 'Cacik', 'Portakal', 'Pilic Kroket'],
['Revani', 'Cacik', 'Bulgur Pilavi', 'Pilic Kroket'],
['Cikolatali Baklava', 'Bulgur Pilavi', 'Cacik', 'Pilic Kroket'],
['CobanSalata', 'Cacik', 'Bulgur Pilavi', 'Pilic Kroket'],
['Ayva Tatlisi', 'Cacik', 'Bulgur Pilavi', 'Pilic Kroket'],
['Portakal', 'Cacik', 'Bulgur Pilavi', 'Pilic Kroket'],
['Sekerpare', 'Cacik', 'Bulgur Pilavi', 'Pilic Kroket'],
['Elma', 'Cacik', 'Bulgur Pilavi', 'Pilic Kroket'],
['Elma', 'Cacik', 'Bulgur Pilavi', 'Pilic Kroket'],
['Yogurt', 'Pirasa', 'Bulgur Pilavi', 'Yesil Mercimek'],
['Armut', 'Cacik', 'Bulgur Pilavi', 'Pilic Kroket'],
['Yogurt', 'Cikolatali Baklava', 'Bulgur Pilavi', 'Yesil Mercimek'],
['Yogurt', 'CobanSalata', 'Bulgur Pilavi', 'Yesil Mercimek'],
['Ayva Tatlisi', 'Yogurt', 'Bulgur Pilavi', 'Yesil Mercimek'],
['Yogurt', 'Sekerpare', 'Bulgur Pilavi', 'Yesil Mercimek'],
['Ayran', 'Revani', 'Bulgur Pilavi', 'Yesil Mercimek'],
['Soguk Cay', 'Revani', 'Bulgur Pilavi', 'Yesil Mercimek'],
['Yogurt', 'Revani', 'Bulgur Pilavi', 'Yesil Mercimek'],
['Meyve Suyu', 'Revani', 'Bulgur Pilavi', 'Yesil Mercimek'],
['Su', 'Revani', 'Bulgur Pilavi', 'Yesil Mercimek'],
['Meyve Suyu', 'Makarna', 'Yesil Mercimek', 'Revani'],
['Makarna', 'Salgam', 'Revani', 'Yesil Mercimek'],
['Makarna', 'Su', 'Revani', 'Yesil Mercimek'],
['Makarna', 'Yesil Mercimek', 'Sekerpare', 'Salgam'],
['Makarna', 'Salgam', 'Cikolatali Baklava', 'Yesil Mercimek'],
['Yesil Mercimek', 'Portakal', 'Makarna', 'Salgam'],
['Yesil Mercimek', 'Ayva Tatlisi', 'Makarna', 'Besamelli Tavuk'],
['Yesil Mercimek', 'Elma', 'Makarna', 'Salgam'],
['Elma', 'Yesil Mercimek', 'Makarna', 'Salgam'],
['Cacik', 'Yesil Mercimek', 'Makarna', 'Salgam'],
['Makarna', 'Yesil Mercimek', 'Armut', 'Salgam'],
['Cigkofte', 'Kola', 'Makarna', 'Yesil Mercimek'],
['Revani', 'Kola', 'Makarna', 'Yesil Mercimek'],
['Cikolatali Baklava', 'Yesil Mercimek', 'Kola', 'Makarna'],
['Enginar', 'Kola', 'Makarna', 'Yesil Mercimek'],
['Armut', 'Kola', 'Makarna', 'Yesil Mercimek'],
['Elma', 'Kola', 'Makarna', 'Yesil Mercimek'],
['Revani', 'Kola', 'Makarna', 'Yesil Mercimek'],
['Meyve Suyu', 'Yesil Mercimek', 'Makarna', 'Cacik'],
['Ayran', 'Yesil Mercimek', 'Makarna', 'Cacik'],
['Ayva Tatlisi', 'Kola', 'Makarna', 'Yesil Mercimek'],
['Pirasa', 'Yesil Mercimek', 'Cacik', 'Makarna'],
['Cacik', 'Makarna', 'Pirasa', 'Yesil Mercimek'],
['Yogurt', 'Yesil Mercimek', 'Cacik', 'Makarna'],
['Cacik', 'Makarna', 'Armut', 'Yesil Mercimek'],
['Cacik', 'Makarna', 'Portakal', 'Yesil Mercimek'],
['Cacik', 'Makarna', 'Revani', 'Yesil Mercimek'],
['Cacik', 'Elma', 'Makarna', 'Yesil Mercimek'],
['Cacik', 'Makarna', 'Sekerpare', 'Yesil Mercimek'],
['Cacik', 'Makarna', 'Yesil Mercimek', 'Cikolatali Baklava'],
['Makarna', 'Portakal', 'Cigkofte', 'Yesil Mercimek'],
['Cacik', 'Makarna', 'Ayva Tatlisi', 'Yesil Mercimek'],
['Cigkofte', 'Sekerpare', 'Makarna', 'Yesil Mercimek'],
['Ayva Tatlisi', 'Cigkofte', 'Makarna', 'Yesil Mercimek'],
['Makarna', 'Yesil Mercimek', 'Revani', 'Cigkofte'],
['Makarna', 'Yesil Mercimek', 'Cikolatali Baklava', 'Cigkofte'],
['Makarna', 'Yesil Mercimek', 'Elma', 'Cigkofte'],
['Makarna', 'Cigkofte', 'Yesil Mercimek', 'Armut'],
['Makarna', 'Cigkofte', 'Yesil Mercimek', 'CobanSalata'],
['Makarna', 'Cigkofte', 'Elma', 'Yesil Mercimek'],
['Cigkofte', 'Yesil Mercimek', 'Yogurt', 'Makarna'],
['Makarna', 'Cigkofte', 'Yesil Mercimek', 'Su'],
['Makarna', 'Cigkofte', 'Yesil Mercimek', 'Meyve Suyu'],
['Cigkofte', 'Makarna', 'Ayran', 'Yesil Mercimek'],
['Makarna', 'Cigkofte', 'Soguk Cay', 'Yesil Mercimek'],
['Meyve Suyu', 'Yesil Mercimek', 'Makarna', 'Cigkofte'],
['Makarna', 'Cigkofte', 'Enginar', 'Yesil Mercimek'],
['Pirinc Pilavi', 'CobanSalata', 'Yesil Mercimek', 'Cigkofte'],
['Pirinc Pilavi', 'Cigkofte', 'Pirasa', 'Yesil Mercimek'],
['Pirinc Pilavi', 'Revani', 'Cigkofte', 'Yesil Mercimek']
]

te = TransactionEncoder()
te_array = te.fit(veriseti).transform(veriseti)
df = pd.DataFrame(te_array, columns=te.columns_)

tuketilenler = apriori(df, min_support=0.01, use_colnames=True)

print(tuketilenler.rename(columns={'itemsets': 'Yiyecek', 'support': 'Destek'}))

kural = association_rules(tuketilenler, metric="confidence", min_threshold=0.01, num_itemsets=len(tuketilenler))

tekli = tuketilenler[tuketilenler['itemsets'].apply(lambda x: len(x) == 1)].sort_values('support', ascending=False).head(1)
ciftli = tuketilenler[tuketilenler['itemsets'].apply(lambda x: len(x) == 2)].sort_values('support', ascending=False).head(1)
uclu = tuketilenler[tuketilenler['itemsets'].apply(lambda x: len(x) == 3)].sort_values('support', ascending=False).head(1)
dortlu = tuketilenler[tuketilenler['itemsets'].apply(lambda x: len(x) == 4)].sort_values('support', ascending=False).head(1)

print("En sık tüketilen tekli ürün:")
print(tekli.rename(columns={'itemsets': 'Yiyecek', 'support': 'Destek'}))

print("\nEn sık birlikte tüketilen ikili ürün:")
print(ciftli.rename(columns={'itemsets': 'Yiyecekler', 'support': 'Destek'}))

print("\nEn sık birlikte tüketilen üçlü ürün:")
print(uclu.rename(columns={'itemsets': 'Yiyecekler', 'support': 'Destek'}))

print("\nEn sık birlikte tüketilen dörtlü ürün:")
print(dortlu.rename(columns={'itemsets': 'Yiyecekler', 'support': 'Destek'}))

print("\nDestek ve güven değerleri:")
print(kural[['antecedents', 'consequents', 'support', 'confidence']].rename(columns={
    'antecedents': 'Öncüller',
    'consequents': 'Sonuçlar',
    'support': 'Destek',
    'confidence': 'Güven'
}))